secret_key_base: THERE WILL ALREADY BE SOME CRAZY STRING HERE. LEAVE IT THERE.
twilio_account_sid:  <%= ENV.fetch("TWILIO_ACCOUNT_SID", "AC519e002dee52f6b3d13009877f642bf1") %>
twilio_auth_token:  <%= ENV.fetch("TWILIO_AUTH_TOKEN", "7af6d3e68dec49ad7528198b619d8c42") %>
twilio_phone_number:  <%= ENV.fetch("TWILIO_PHONE_NUMBER", "YOUR-TWILIO-TRIAL-PHONE-NUMBER-GOES-HERE") %>ACCOUNT SID
